### ISSUE TITLE
Pytest dependency

### ISSUE THREAD

**Issue by pawel-czyz** [grfrederic/subplots-from-axsize#1]
Hi @grfrederic, cool package! Currently `subplots_from_axsize` requires `pytest` as a core dependency. Would it be possible to add it as an optional dependency, e.g., by creating [a new group](https://python-poetry.org/docs/master/managing-dependencies/)?

**Comment by grfrederic** [comment]
thanks, good point! take a look, i think it should work now?

**Comment by grfrederic** [comment]
yes it does, checked on pip!
